name: "Tests and Release on push to main"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]
jobs:
  tests:
    name: Run tests + coverage
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/20"
      - name: Install dependencies
        run: npm install
      - name: Run check
        run: npm run check
      - name: Run tests
        run: npm run test
  release:
    runs-on: ubuntu-24.04
    name: Release if on main branch
    needs: tests
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/20"
      - name: Install semantic-release
        run: npm install -g semantic-release conventional-changelog-conventionalcommits
      - name: Release if running on main
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
